FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim

COPY . /app

WORKDIR /app

RUN yes | pip install --upgrade --no-cache-dir -r builder/requirements.txt

ENV PLEXAPI_PLEXAPI_ENABLE_FAST_CONNECT=true \
    PLEXAPI_AUTH_SRV_NAME="Project: Atlas" \
    PLEXAPI_PLEXAPI_CONTAINER_SIZE=1000 \
    DB_PROJECT=plex-project-atlas \
    DB_REGION=europe-west3
